//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1Cambealo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int id { get; set; }
        public Nullable<int> productoOfrecido { get; set; }
        public Nullable<int> productoInteres { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
    }
}
